Feature/frontend
piekaa/JankowskiMatches pull request #15
Opened 2021-01-18 10:37 UTC by Frexor

2021-01-18 10:40 UTC, piekaa requested changes

2021-01-18 10:40 UTC, piekaa commented on src/main/resources/static/index.html
> +      document.getElementById("solutionBox").value;
that is this line doing?

2021-01-22 12:04 UTC, Frexor commented on src/main/resources/static/index.html
> +      document.getElementById("solutionBox").value;
Done. Deleted 40 line.

2021-01-22 13:40 UTC, piekaa approved these changes
debesta

2021-01-22 13:40 UTC, merged